version: '3.8'

services:

  service:
    container_name: segments_service
    build:
      context: ../
      dockerfile: build/docker/service/Dockerfile
    restart: unless-stopped
    ports:
      - ${SERVICE_PORT}:${SERVICE_PORT}
    links:
      - db
      - kafka
    depends_on:
      - db
      - kafka
    env_file:
      .env

  db:
    container_name: segments_db
    build:
      context: ../build/docker/db
      dockerfile: ./Dockerfile
    restart: unless-stopped
    volumes:
      - pgs_segments_volume:/var/lib/postgresql/data
    ports:
      - "5400:5432"
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB

  kafka:
    container_name: segments_kafka
    image: bitnami/kafka:3.4.1
    restart: unless-stopped
    volumes:
      - kafka_segments_volume:/bitnami/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_KRAFT_CLUSTER_ID: abcdefghijklmnopqrstuv
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka:9093
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER


volumes:
  pgs_segments_volume:
  kafka_segments_volume: