version: '3.8'

services:

  service:
    container_name: segments_service
    build:
      context: ../
      dockerfile: build/docker/service/Dockerfile
    restart: unless-stopped
    ports:
      - ${SERVICE_PORT}:${SERVICE_PORT}
    links:
      - db
    depends_on:
      - db
    env_file:
      .env

  db:
    container_name: segments_db
    build:
      context: ../build/docker/db
      dockerfile: ./Dockerfile
    restart: unless-stopped
    volumes:
      - pgs_segments_volume:/var/lib/postgresql/data
    ports:
      - "5400:5432"
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB

volumes:
  pgs_segments_volume: